#!/usr/bin/env python3
"""
Siva Pest Control — Website Audit Report (PDF)
Generates a comprehensive multi-page PDF audit report covering:
  - Executive summary
  - Website audit
  - SEO audit
  - UI/UX audit
  - CSS audit
  - Google Analytics 4 integration summary
  - Applied fixes summary
  - Prioritized action items

Output: /home/z/my-project/download/siva-pest-control-audit-report.pdf
"""

import os
import sys
import hashlib
from pathlib import Path

# ---- ReportLab imports ----
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm, cm
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT, TA_JUSTIFY
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle,
    KeepTogether, Image, Flowable, HRFlowable
)
from reportlab.platypus.tableofcontents import TableOfContents
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfgen import canvas

# ---- Font registration (CJK-safe + branded typography) ----
FONT_DIRS = [
    "/usr/share/fonts/truetype/noto-serif-sc",
    "/usr/share/fonts/truetype/chinese",
    "/usr/share/fonts/truetype/english",
    "/usr/share/fonts/truetype/dejavu",
]

def register_fonts():
    """Register Noto Serif SC + DejaVu fallback. Uses serif throughout since
    Inter/Manrope are not installed locally — editorial feel suits an audit report."""
    try:
        # Body serif (Noto Serif SC for CJK + Latin)
        pdfmetrics.registerFont(TTFont(
            "BodySerif",
            "/usr/share/fonts/truetype/noto-serif-sc/NotoSerifSC-Regular.ttf"
        ))
        pdfmetrics.registerFont(TTFont(
            "BodySerifBold",
            "/usr/share/fonts/truetype/noto-serif-sc/NotoSerifSC-Bold.ttf"
        ))
        # Display uses ExtraBold weight for strong headlines
        pdfmetrics.registerFont(TTFont(
            "DisplayFont",
            "/usr/share/fonts/truetype/noto-serif-sc/NotoSerifSC-ExtraBold.ttf"
        ))
        pdfmetrics.registerFont(TTFont(
            "DisplayFontBold",
            "/usr/share/fonts/truetype/noto-serif-sc/NotoSerifSC-Black.ttf"
        ))
        # Mono fallback
        pdfmetrics.registerFont(TTFont(
            "Mono",
            "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"
        ))
        # Map font families
        from reportlab.pdfbase.pdfmetrics import registerFontFamily
        registerFontFamily(
            "BodySerif",
            normal="BodySerif",
            bold="BodySerifBold",
            italic="BodySerif",
            boldItalic="BodySerifBold",
        )
        registerFontFamily(
            "DisplayFont",
            normal="DisplayFont",
            bold="DisplayFontBold",
            italic="DisplayFont",
            boldItalic="DisplayFontBold",
        )
        return True
    except Exception as e:
        print(f"Font registration warning: {e}", file=sys.stderr)
        return False

FONTS_OK = register_fonts()
BODY_FONT = "BodySerif" if FONTS_OK else "Helvetica"
BODY_FONT_BOLD = "BodySerifBold" if FONTS_OK else "Helvetica-Bold"
DISPLAY_FONT = "DisplayFont" if FONTS_OK else "Helvetica-Bold"
DISPLAY_FONT_BOLD = "DisplayFontBold" if FONTS_OK else "Helvetica-Bold"
DISPLAY_FONT_REG = "DisplayFont" if FONTS_OK else "Helvetica"
MONO_FONT = "Mono" if FONTS_OK else "Courier"

# ━━ Cascade Palette (auto-generated by design_engine.py palette-cascade) ━━
# XL tier: backgrounds (area > 50%, S ≤ 0.08)
PAGE_BG       = colors.HexColor('#f7f6f6')
SECTION_BG    = colors.HexColor('#efefed')

# L tier: surfaces (area 20-50%, S ≤ 0.15)
CARD_BG       = colors.HexColor('#e9e8e3')
TABLE_STRIPE  = colors.HexColor('#ecebe8')

# M tier: structural fills (area 5-20%, S ≤ 0.30)
HEADER_FILL   = colors.HexColor('#7b6f4e')
COVER_BLOCK   = colors.HexColor('#7d7660')

# S tier: edges & icons (area 1-5%, S ≤ 0.50)
BORDER        = colors.HexColor('#bebaaf')
ICON          = colors.HexColor('#8a7536')

# XS tier: emphasis (area < 1%, S ≤ 0.75)
ACCENT        = colors.HexColor('#96781b')
ACCENT_2      = colors.HexColor('#3f98b6')

# Typography
TEXT_PRIMARY   = colors.HexColor('#161614')
TEXT_MUTED     = colors.HexColor('#8e8c85')

# Semantic (low-saturation, area-appropriate)
SEM_SUCCESS   = colors.HexColor('#497c5a')
SEM_WARNING   = colors.HexColor('#b18f4d')
SEM_ERROR     = colors.HexColor('#a34f47')
SEM_INFO      = colors.HexColor('#4c6884')

# Brand accent (matches site's safety orange)
BRAND_ORANGE  = colors.HexColor('#D77005')
BRAND_BROWN   = colors.HexColor('#332416')
BRAND_TEAL    = colors.HexColor('#719899')

# Override accent for this report — use brand orange
ACCENT = BRAND_ORANGE

# ━━ Page layout ━━
PAGE_W, PAGE_H = A4
MARGIN_L = 22 * mm
MARGIN_R = 22 * mm
MARGIN_T = 22 * mm
MARGIN_B = 22 * mm
CONTENT_W = PAGE_W - MARGIN_L - MARGIN_R

# ━━ Styles ━━
def make_styles():
    s = {}
    s['cover_title'] = ParagraphStyle(
        'CoverTitle', fontName=DISPLAY_FONT, fontSize=34, leading=40,
        textColor=colors.white, alignment=TA_LEFT, spaceAfter=8,
    )
    s['cover_subtitle'] = ParagraphStyle(
        'CoverSubtitle', fontName=DISPLAY_FONT_REG, fontSize=16, leading=22,
        textColor=colors.HexColor('#F0E6D2'), alignment=TA_LEFT,
    )
    s['cover_meta'] = ParagraphStyle(
        'CoverMeta', fontName=BODY_FONT, fontSize=10, leading=14,
        textColor=colors.HexColor('#D8C9A8'), alignment=TA_LEFT,
    )
    s['cover_tag'] = ParagraphStyle(
        'CoverTag', fontName=DISPLAY_FONT_BOLD, fontSize=9, leading=12,
        textColor=BRAND_ORANGE, alignment=TA_LEFT,
    )
    s['h1'] = ParagraphStyle(
        'H1', fontName=DISPLAY_FONT, fontSize=22, leading=28,
        textColor=BRAND_BROWN, alignment=TA_LEFT,
        spaceBefore=14, spaceAfter=10,
    )
    s['h2'] = ParagraphStyle(
        'H2', fontName=DISPLAY_FONT, fontSize=16, leading=22,
        textColor=BRAND_BROWN, alignment=TA_LEFT,
        spaceBefore=14, spaceAfter=8, keepWithNext=True,
    )
    s['h3'] = ParagraphStyle(
        'H3', fontName=DISPLAY_FONT, fontSize=13, leading=18,
        textColor=HEADER_FILL, alignment=TA_LEFT,
        spaceBefore=10, spaceAfter=6, keepWithNext=True,
    )
    s['h4'] = ParagraphStyle(
        'H4', fontName=BODY_FONT_BOLD, fontSize=11, leading=15,
        textColor=ACCENT, alignment=TA_LEFT,
        spaceBefore=8, spaceAfter=4, keepWithNext=True,
    )
    s['body'] = ParagraphStyle(
        'Body', fontName=BODY_FONT, fontSize=10, leading=15,
        textColor=TEXT_PRIMARY, alignment=TA_JUSTIFY,
        spaceAfter=6, firstLineIndent=0,
    )
    s['body_left'] = ParagraphStyle(
        'BodyLeft', fontName=BODY_FONT, fontSize=10, leading=15,
        textColor=TEXT_PRIMARY, alignment=TA_LEFT,
        spaceAfter=6,
    )
    s['lead'] = ParagraphStyle(
        'Lead', fontName=BODY_FONT, fontSize=11, leading=17,
        textColor=TEXT_PRIMARY, alignment=TA_LEFT,
        spaceAfter=10,
    )
    s['bullet'] = ParagraphStyle(
        'Bullet', fontName=BODY_FONT, fontSize=10, leading=14,
        textColor=TEXT_PRIMARY, alignment=TA_LEFT,
        leftIndent=14, bulletIndent=4, spaceAfter=3,
    )
    s['caption'] = ParagraphStyle(
        'Caption', fontName=BODY_FONT, fontSize=8.5, leading=12,
        textColor=TEXT_MUTED, alignment=TA_LEFT,
    )
    s['code'] = ParagraphStyle(
        'Code', fontName=MONO_FONT, fontSize=8.5, leading=12,
        textColor=BRAND_BROWN, alignment=TA_LEFT,
        leftIndent=8, rightIndent=8,
        backColor=CARD_BG, borderColor=BORDER, borderWidth=0.5,
        borderPadding=6, spaceAfter=6,
    )
    s['callout_title'] = ParagraphStyle(
        'CalloutTitle', fontName=DISPLAY_FONT, fontSize=10, leading=14,
        textColor=colors.white, alignment=TA_LEFT,
    )
    s['callout_body'] = ParagraphStyle(
        'CalloutBody', fontName=BODY_FONT, fontSize=9.5, leading=14,
        textColor=colors.white, alignment=TA_LEFT,
    )
    s['toc1'] = ParagraphStyle(
        'TOC1', fontName=DISPLAY_FONT, fontSize=11, leading=16,
        textColor=BRAND_BROWN, leftIndent=0,
    )
    s['toc2'] = ParagraphStyle(
        'TOC2', fontName=BODY_FONT, fontSize=10, leading=14,
        textColor=TEXT_PRIMARY, leftIndent=16,
    )
    s['score_label'] = ParagraphStyle(
        'ScoreLabel', fontName=DISPLAY_FONT_BOLD, fontSize=8, leading=10,
        textColor=TEXT_MUTED, alignment=TA_CENTER,
    )
    s['score_value'] = ParagraphStyle(
        'ScoreValue', fontName=DISPLAY_FONT, fontSize=22, leading=24,
        textColor=ACCENT, alignment=TA_CENTER,
    )
    return s

STYLES = make_styles()


# ━━ Cover page (custom canvas) ━━
def draw_cover(canvas, doc):
    """Custom cover page drawn directly on canvas."""
    c = canvas
    # Full-bleed dark background
    c.setFillColor(BRAND_BROWN)
    c.rect(0, 0, PAGE_W, PAGE_H, fill=1, stroke=0)

    # Decorative gradient orbs (simulated with concentric circles)
    # Top-right teal glow
    for i in range(20, 0, -1):
        alpha = 0.015 * (20 - i + 1)
        c.setFillColorRGB(0.44, 0.60, 0.60, alpha=alpha)
        c.circle(PAGE_W - 30*mm, PAGE_H - 50*mm, i * 4 * mm, fill=1, stroke=0)

    # Bottom-left orange glow
    for i in range(20, 0, -1):
        alpha = 0.025 * (20 - i + 1)
        c.setFillColorRGB(0.84, 0.44, 0.02, alpha=alpha)
        c.circle(40*mm, 60*mm, i * 5 * mm, fill=1, stroke=0)

    # Subtle grid pattern (background)
    c.setStrokeColor(colors.HexColor('#4A3624'))
    c.setLineWidth(0.3)
    grid_size = 14 * mm
    for x in range(0, int(PAGE_W / grid_size) + 1):
        c.line(x * grid_size, 0, x * grid_size, PAGE_H)
    for y in range(0, int(PAGE_H / grid_size) + 1):
        c.line(0, y * grid_size, PAGE_W, y * grid_size)

    # Top brand strip — orange accent bar
    c.setFillColor(BRAND_ORANGE)
    c.rect(0, PAGE_H - 8*mm, PAGE_W, 8*mm, fill=1, stroke=0)

    # Logo + brand label top-left
    c.setFillColor(colors.white)
    c.setFont(DISPLAY_FONT, 11)
    c.drawString(MARGIN_L, PAGE_H - 18*mm, "SIVA PEST CONTROL")
    c.setFillColor(colors.HexColor('#D8AE7F'))
    c.setFont(BODY_FONT, 8)
    c.drawString(MARGIN_L, PAGE_H - 24*mm, "Protection. Science. Trust.")

    # Date top-right
    c.setFillColor(colors.HexColor('#D8C9A8'))
    c.setFont(BODY_FONT, 9)
    c.drawRightString(PAGE_W - MARGIN_R, PAGE_H - 18*mm, "Audit Report")
    c.drawRightString(PAGE_W - MARGIN_R, PAGE_H - 24*mm, "August 2026")

    # Main title block (centered vertically)
    title_y = PAGE_H * 0.55
    c.setFillColor(BRAND_ORANGE)
    c.setFont(DISPLAY_FONT, 9)
    c.drawString(MARGIN_L, title_y + 70, "COMPREHENSIVE AUDIT")

    c.setFillColor(colors.white)
    c.setFont(DISPLAY_FONT, 36)
    c.drawString(MARGIN_L, title_y + 36, "Website, SEO, UI/UX,")
    c.drawString(MARGIN_L, title_y, "CSS Audit + GA4")

    c.setFillColor(colors.HexColor('#F4B266'))
    c.setFont(DISPLAY_FONT, 22)
    c.drawString(MARGIN_L, title_y - 30, "Integration Report")

    # Subtitle
    c.setFillColor(colors.HexColor('#E8D2B5'))
    c.setFont(BODY_FONT, 11)
    c.drawString(MARGIN_L, title_y - 55,
                 "Siva Pest Control — sivapestcontrol.com")
    c.drawString(MARGIN_L, title_y - 70,
                 "Hyderabad · Chennai · Bangalore")

    # Score badges at bottom
    badge_y = 90 * mm
    badges = [
        ("UI/UX", "6.6", "/10"),
        ("SEO", "5.4", "/10"),
        ("CSS", "5.5", "/10"),
    ]
    badge_w = 50 * mm
    badge_gap = 8 * mm
    total_badge_w = len(badges) * badge_w + (len(badges) - 1) * badge_gap
    start_x = (PAGE_W - total_badge_w) / 2

    for i, (label, score, suffix) in enumerate(badges):
        x = start_x + i * (badge_w + badge_gap)
        # Card background
        c.setFillColor(colors.HexColor('#4A3624'))
        c.setStrokeColor(colors.HexColor('#D77005'))
        c.setLineWidth(0.6)
        c.roundRect(x, badge_y - 20, badge_w, 50, 6, fill=1, stroke=1)

        # Label
        c.setFillColor(colors.HexColor('#D8C9A8'))
        c.setFont(DISPLAY_FONT, 8)
        c.drawCentredString(x + badge_w/2, badge_y + 22, label.upper())

        # Score
        c.setFillColor(BRAND_ORANGE)
        c.setFont(DISPLAY_FONT, 22)
        c.drawCentredString(x + badge_w/2, badge_y - 5, score)
        # Suffix
        score_width = c.stringWidth(score, DISPLAY_FONT, 22)
        c.setFillColor(colors.HexColor('#A89878'))
        c.setFont(BODY_FONT, 10)
        c.drawString(x + badge_w/2 + score_width/2 + 2, badge_y - 5, suffix)

    # Bottom strip — meta info
    bottom_y = 30 * mm
    c.setStrokeColor(colors.HexColor('#4A3624'))
    c.setLineWidth(0.5)
    c.line(MARGIN_L, bottom_y + 18, PAGE_W - MARGIN_R, bottom_y + 18)

    c.setFillColor(colors.HexColor('#D8C9A8'))
    c.setFont(BODY_FONT, 8)
    c.drawString(MARGIN_L, bottom_y + 8, "Prepared by:")
    c.setFillColor(colors.white)
    c.setFont(DISPLAY_FONT, 9)
    c.drawString(MARGIN_L, bottom_y, "Super Z — AI Engineering Audit")

    c.setFillColor(colors.HexColor('#D8C9A8'))
    c.setFont(BODY_FONT, 8)
    c.drawRightString(PAGE_W - MARGIN_R, bottom_y + 8, "Document version:")
    c.setFillColor(colors.white)
    c.setFont(DISPLAY_FONT, 9)
    c.drawRightString(PAGE_W - MARGIN_R, bottom_y, "v1.0 — August 8, 2026")


# ━━ Page header/footer for body pages ━━
def draw_body_chrome(canvas, doc):
    """Draw header and footer on body pages."""
    c = canvas
    # Top header strip
    c.setFillColor(BRAND_BROWN)
    c.rect(0, PAGE_H - 12*mm, PAGE_W, 12*mm, fill=1, stroke=0)
    # Orange accent line
    c.setFillColor(BRAND_ORANGE)
    c.rect(0, PAGE_H - 13*mm, PAGE_W, 1*mm, fill=1, stroke=0)

    # Header text
    c.setFillColor(colors.HexColor('#E8D2B5'))
    c.setFont(DISPLAY_FONT, 8)
    c.drawString(MARGIN_L, PAGE_H - 8*mm, "SIVA PEST CONTROL — AUDIT REPORT")
    c.setFillColor(colors.HexColor('#A89878'))
    c.setFont(BODY_FONT, 8)
    c.drawRightString(PAGE_W - MARGIN_R, PAGE_H - 8*mm, "v1.0 · Aug 2026")

    # Footer
    c.setStrokeColor(BORDER)
    c.setLineWidth(0.4)
    c.line(MARGIN_L, 15*mm, PAGE_W - MARGIN_R, 15*mm)

    c.setFillColor(TEXT_MUTED)
    c.setFont(BODY_FONT, 8)
    c.drawString(MARGIN_L, 10*mm, "sivapestcontrol.com")
    c.drawCentredString(PAGE_W/2, 10*mm, f"Page {doc.page}")
    c.drawRightString(PAGE_W - MARGIN_R, 10*mm, "Confidential — Internal Use")


# ━━ Custom Flowables ━━
class ScoreCard(Flowable):
    """A small card showing a score and label."""
    def __init__(self, label, score, total="/10", color=ACCENT, width=55*mm, height=22*mm):
        Flowable.__init__(self)
        self.label = label
        self.score = score
        self.total = total
        self.color = color
        self.width = width
        self.height = height

    def draw(self):
        c = self.canv
        # Background
        c.setFillColor(CARD_BG)
        c.setStrokeColor(BORDER)
        c.setLineWidth(0.5)
        c.roundRect(0, 0, self.width, self.height, 4, fill=1, stroke=1)
        # Label
        c.setFillColor(TEXT_MUTED)
        c.setFont(DISPLAY_FONT_BOLD, 7.5)
        c.drawString(6, self.height - 8, self.label.upper())
        # Score
        c.setFillColor(self.color)
        c.setFont(DISPLAY_FONT, 18)
        c.drawString(6, 5, str(self.score))
        # Total suffix
        score_w = c.stringWidth(str(self.score), DISPLAY_FONT, 18)
        c.setFillColor(TEXT_MUTED)
        c.setFont(BODY_FONT, 9)
        c.drawString(6 + score_w + 2, 7, self.total)


class CalloutBox(Flowable):
    """A colored callout box with title + body."""
    def __init__(self, title, body, kind='info', width=CONTENT_W):
        Flowable.__init__(self)
        self.title = title
        self.body = body
        self.kind = kind
        self.width = width
        # Compute height based on wrapped text
        self.title_p = Paragraph(f"<b>{title}</b>", STYLES['callout_title'])
        self.body_p = Paragraph(body, STYLES['callout_body'])
        # Measure
        from reportlab.lib.styles import ParagraphStyle
        temp_w = width - 16
        self._title_w, self._title_h = self.title_p.wrap(temp_w, 1000)
        self._body_w, self._body_h = self.body_p.wrap(temp_w, 1000)
        self.height = self._title_h + self._body_h + 18

    def draw(self):
        c = self.canv
        # Background color by kind
        if self.kind == 'critical':
            bg = SEM_ERROR
            border = colors.HexColor('#C4482A')
        elif self.kind == 'warning':
            bg = SEM_WARNING
            border = colors.HexColor('#D4A957')
        elif self.kind == 'success':
            bg = SEM_SUCCESS
            border = colors.HexColor('#6BA078')
        else:  # info
            bg = SEM_INFO
            border = colors.HexColor('#6E8AAA')

        # Rounded background
        c.setFillColor(bg)
        c.setStrokeColor(border)
        c.setLineWidth(0.5)
        c.roundRect(0, 0, self.width, self.height, 4, fill=1, stroke=1)

        # Left accent bar
        c.setFillColor(colors.white)
        c.rect(0, 0, 3, self.height, fill=1, stroke=0)

        # Draw title + body
        self.title_p.drawOn(c, 8, self.height - 8 - self._title_h)
        self.body_p.drawOn(c, 8, 8)


def hrule(color=BORDER, thickness=0.5, space_before=4, space_after=4):
    return HRFlowable(width="100%", thickness=thickness, color=color,
                       spaceBefore=space_before, spaceAfter=space_after)


# ━━ TOC DocTemplate ━━
class TocDocTemplate(SimpleDocTemplate):
    def afterFlowable(self, flowable):
        if hasattr(flowable, 'bookmark_name'):
            level = getattr(flowable, 'bookmark_level', 0)
            text = getattr(flowable, 'bookmark_text', '')
            key = getattr(flowable, 'bookmark_key', '')
            self.notify('TOCEntry', (level, text, self.page, key))


def add_heading(text, style, level=0):
    """Create a heading paragraph with TOC bookmark."""
    key = f'h_{hashlib.md5(text.encode()).hexdigest()[:8]}'
    p = Paragraph(f'<a name="{key}"/>{text}', style)
    p.bookmark_name = key
    p.bookmark_level = level
    p.bookmark_text = text
    p.bookmark_key = key
    return p


def bullet_list(items, style=None):
    """Convert a list of strings into bullet paragraphs."""
    style = style or STYLES['bullet']
    return [Paragraph(f"• {item}", style) for item in items]


def two_col_score_row(label, score, max_score=10):
    """A two-column row showing a label and its score."""
    score_color = SEM_ERROR if score < 5 else (SEM_WARNING if score < 7 else (SEM_SUCCESS if score >= 8 else ACCENT))
    score_text = f'<font color="{score_color.hexval()}"><b>{score}</b></font><font color="{TEXT_MUTED.hexval()}">/{max_score}</font>'
    table = Table(
        [[Paragraph(label, STYLES['body_left']),
          Paragraph(score_text, ParagraphStyle('Score', parent=STYLES['body_left'], alignment=TA_RIGHT))]],
        colWidths=[CONTENT_W * 0.75, CONTENT_W * 0.25],
    )
    table.setStyle(TableStyle([
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('LINEBELOW', (0, 0), (-1, -1), 0.3, BORDER),
        ('BACKGROUND', (0, 0), (-1, -1), colors.white),
    ]))
    return table


def findings_table(rows, col_widths=None):
    """Build a table with a header row and zebra striping.
    rows: list of lists (first row is header)
    """
    if col_widths is None:
        n = len(rows[0])
        col_widths = [CONTENT_W / n] * n

    # Wrap cell text in Paragraphs for word-wrap
    wrapped = []
    for r_idx, row in enumerate(rows):
        wrapped_row = []
        for c_idx, cell in enumerate(row):
            if isinstance(cell, Paragraph):
                wrapped_row.append(cell)
            else:
                if r_idx == 0:
                    # Header
                    wrapped_row.append(Paragraph(
                        f"<b>{cell}</b>",
                        ParagraphStyle('ThCell', fontName=DISPLAY_FONT_BOLD,
                                       fontSize=9, leading=12,
                                       textColor=colors.white, alignment=TA_LEFT)
                    ))
                else:
                    wrapped_row.append(Paragraph(
                        str(cell),
                        ParagraphStyle('TdCell', fontName=BODY_FONT,
                                       fontSize=8.5, leading=12,
                                       textColor=TEXT_PRIMARY, alignment=TA_LEFT)
                    ))
        wrapped.append(wrapped_row)

    t = Table(wrapped, colWidths=col_widths, repeatRows=1)
    style = [
        ('BACKGROUND', (0, 0), (-1, 0), HEADER_FILL),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('GRID', (0, 0), (-1, -1), 0.3, BORDER),
    ]
    # Zebra striping
    for i in range(1, len(rows)):
        if i % 2 == 0:
            style.append(('BACKGROUND', (0, i), (-1, i), TABLE_STRIPE))
        else:
            style.append(('BACKGROUND', (0, i), (-1, i), colors.white))
    t.setStyle(TableStyle(style))
    return t


def callout(title, body, kind='info'):
    return CalloutBox(title, body, kind=kind)


def section_break():
    return Spacer(1, 10)
