#!/usr/bin/env python3
"""Update pest image paths in src/data/pests.ts to use new colony/infestation photos."""

import re
from pathlib import Path

PESTS_FILE = Path("/home/z/my-project/src/data/pests.ts")

# Map slug -> new image path (generated by scripts/generate_pest_images.sh)
SLUG_TO_IMAGE = {
    "german-cockroach":      "/images/pests/german-cockroach.jpg",
    "american-cockroach":    "/images/pests/american-cockroach.jpg",
    "subterranean-termite":  "/images/pests/subterranean-termite.jpg",
    "house-rat":             "/images/pests/house-rat.jpg",
    "aedes-mosquito":        "/images/pests/aedes-mosquito.jpg",
    "bed-bug":               "/images/pests/bed-bug.jpg",
    "house-spider":          "/images/pests/house-spider.jpg",
    "pigeon":                "/images/pests/rock-pigeon.jpg",
    "red-wasp":              "/images/pests/red-wasp.jpg",
    "pharaoh-ant":           "/images/pests/pharaoh-ant.jpg",
    "black-crazy-ant":       "/images/pests/black-crazy-ant.jpg",
    "carpenter-ant":         "/images/pests/carpenter-ant.jpg",
    "anopheles-mosquito":    "/images/pests/anopheles-mosquito.jpg",
    "culex-mosquito":        "/images/pests/culex-mosquito.jpg",
    "housefly":              "/images/pests/housefly.jpg",
    "fruit-fly":             "/images/pests/fruit-fly.jpg",
    "house-mouse":           "/images/pests/house-mouse.jpg",
    "bandicoot-rat":         "/images/pests/bandicoot-rat.jpg",
    "silverfish":            "/images/pests/silverfish.jpg",
    "powderpost-beetle":     "/images/pests/powderpost-beetle.jpg",
    "indian-honey-bee":      "/images/pests/indian-honey-bee.jpg",
    "common-house-gecko":    "/images/pests/common-house-gecko.jpg",
    "rat-snake":             "/images/pests/rat-snake.jpg",
    "spectacled-cobra":      "/images/pests/spectacled-cobra.jpg",
    # newly added pests already have correct paths in the file
}

# Read the file
text = PESTS_FILE.read_text()

# Pattern: match `slug: "..."` followed (within ~3 lines) by `image: "..."`
# We process entry-by-entry. Strategy: find each `slug: "<slug>"` and the next
# `image: "<...>"` line within the same object, then replace the image path
# if the slug is in our map.

def replace_image_for_slug(text: str, slug: str, new_image: str) -> str:
    """Find the entry with `slug: "{slug}"` and replace its image path."""
    # Match the slug line (note: slug value is followed by , not just newline)
    slug_pattern = re.compile(rf'(slug:\s*"{re.escape(slug)}"\s*,?\s*\n)')
    match = slug_pattern.search(text)
    if not match:
        print(f"  WARN: slug '{slug}' not found")
        return text

    # Find the next `image: "..."` after the slug
    after = text[match.end():]
    img_match = re.search(r'image:\s*"([^"]+)"', after)
    if not img_match:
        print(f"  WARN: image not found for slug '{slug}'")
        return text

    # Replace just that image line
    abs_start = match.end() + img_match.start()
    abs_end = match.end() + img_match.end()
    old_line = text[abs_start:abs_end]
    new_line = f'image: "{new_image}"'
    print(f"  {slug}: {img_match.group(1)} -> {new_image}")
    return text[:abs_start] + new_line + text[abs_end:]

# Apply replacements
for slug, image in SLUG_TO_IMAGE.items():
    text = replace_image_for_slug(text, slug, image)

# Write back
PESTS_FILE.write_text(text)
print(f"\nDone. {len(SLUG_TO_IMAGE)} pest image paths updated.")
